version: '3.8'

services:
  app:
    build: .
    container_name: app_container
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: FanOne
      GRPC_ADDRESS: "127.0.0.1:10001"
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: memorandum
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_CHARSET: utf8mb4
      ETCD_ADDRESS: etcd:2379
      REDIS_ADDRESS: redis:6379
      REDIS_PASSWORD: ""
    depends_on:
      - mysql
      - redis
      - etcd

  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: memorandum
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  etcd:
    image: bitnami/etcd:latest
    container_name: etcd_container
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379"
    volumes:
      - etcd_data:/bitnami/etcd

volumes:
  mysql_data:
  redis_data:
  etcd_data:
